# Trust policy for xor-agent Cloud Run service
# Allows xor-agent to get GitHub tokens via octo-sts
#
# Per DRR-2026-01-13-xor-agent-github-integration.md

# GCP Cloud Run workload identity
issuer: https://accounts.google.com
subject: "631337839690-compute@developer.gserviceaccount.com"

# Alternative: Match any service account from our project
# subject_pattern: ".*@morphysm-fb70d.iam.gserviceaccount.com"

# Permissions granted to xor-agent
permissions:
  contents: write    # Read/write repository contents
  issues: write      # Create/update issues and comments
  pull_requests: write  # Create/update PRs
  workflows: write   # Trigger workflows
